### ISSUE TITLE
Add event yearcalendar.

### ISSUE THREAD

**Issue by jacobomd** [ik024/CalendarLibrary#4]
How to add events to the calendar of the year in the list just like in the calendar of the month.
Thank's you

**Comment by ik024** [comment]
I have added support for adding event list to year view as well.  Please refer to YearViewDemo.java class for more details:
https://github.com/ik024/CalendarLibrary/blob/master/app/src/main/java/com/github/ik024/YearViewDemo.java

Also, dont forget to to update the lib version in your gradle file current version is 2.0.2. Check the read me doc.

Thanks
