### ISSUE TITLE
Year view - with scroll vertical option

### ISSUE THREAD

**Issue by Nidhee** [ik024/CalendarLibrary#5]
Can we have Slide(scroll) up or slide(scroll) down to see months from next & previous years. instead of left and right arrow buttons.

Can you please guide how to do it in this library.

**Comment by ismkhanh** [comment]
You can. Use the MonthView class's setSelectedYear() and setSelectedMonth() for your purpose.

**Comment by Nidhee** [comment]
I am not able to understand your solution. 
how to create year view vertically scrollable which has endless previous and upcoming years ? Right now if we need to change year either click left of right arrow button.

**Comment by ismkhanh** [comment]
This lib doesn't have the logic for scrolling. What I am suggesting is, if you look at the source code you will find a MonthView class which contains setSelectedYear() and setSelectedMonth() method. You can make use of this methods for your purpose. But you need to write logic on your own. 

To give you an idea:
You make use of recycler view/ list view and initially set the count to 12 (as in 12 months of a year). Each row/item of the list contains MonthView and in getView() method of your adapter class you set the year and month. Once the user reaches to the bottom of the list you can show the next 12 months.
